language: node_js
node_js:
  - "0.10"

before_script:
  - npm install -g grunt-cli

script:
  - grunt test

after_script:
  - cat ./test/coverage/report-lcov/lcov.info | ./node_modules/coveralls/bin/coveralls.js
